import Exercises from "@/components/exercise/Exercises";
import WorkoutPlan from "@/components/workout/WorkoutPlan";

import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>FitGenLive.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Exercises />
      <WorkoutPlan />
    </>
  );
}
